AWSTemplateFormatVersion: "2010-09-09"

Description: This template creates Redshift cluster

Parameters:
  ClusterIdentifier:
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Must begin with a alphabet, can have hypen in middle but not at end or at start. Cna also have numeric charters in middle or end.
    Default: Redshift-cluster
    Description: Cluster identifier name
    MaxLength: 60
    MinLength: 1
    Type: String
  
  ClusterType:
    Type: String
    Default: multi-node

  ParameterGroupName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /provisioning/services/default/redshift/ParamGroup

  SubnetGroupName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /provisioning/services/default/rds/DBSubnetGroupName
  
  KMSKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /provisioning/core/account/kms/RedshiftEncryptionCMKArn

  MultiAZSetting:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /provisioning/services/default/rds/MultiAZSetting
  
  DatabaseName:
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Must begin with a alphabet, can have hypen in middle but not at end or at start. Cna also have numeric charters in middle or end.
    Default: myredshiftdb
    Description: redshift database name
    MaxLength: 64
    MinLength: 1
    Type: String
  
  DatabaseMasterUser:
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: Must begin with a alphabet, can have hypen in middle but not at end or at start. Can also have numeric charters in middle or end. The user name can't be 'PUBLIC'.
    Default: redshift-admin
    Description: db admin username
    MaxLength: 128
    MinLength: 1
    NoEcho: false
    Type: String

  DatabaseMasterPassword:
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: alpha-numeric string
    Default: 91365335
    Description: db admin password
    MaxLength: 128
    MinLength: 8
    NoEcho: true
    Type: String



Resources:
  Type: AWS::Redshift::Cluster
  Properties:
    AllowVersionUpgrade: 
      Description: If true, major version upgrades can be applied during the maintenance window.
      AllowedValues:
        - true
        - false
      Type: Boolean
      Default: true

    AutomatedSnapshotRetentionPeriod:
      ConstraintDescription: Must be a value from 0 to 35. Can't be set to 0 if the DB instance is a source to read replicas
      Type: Integer
      Description: The number of days the snapshot will retain.
      MaxValue: 35
      MinValue: 0
      Default: 30
    
    AvailabilityZone:
      Description: The EC2 Availability Zone (AZ) in which you want Amazon Redshift to provision the cluster.
      Default: us-east-1a
      Type: String
      AllowedValues:
        - us-east-1a
        - us-east-1b
        - us-east-1c
    
    AvailabilityZoneRelocation: 
      Description: The option to enable relocation for an Amazon Redshift cluster between Availability Zones after the cluster is created.
      Type: Boolean
      Default: true
    
    AvailabilityZoneRelocationStatus:
      Description: Describes the status of the Availability Zone relocation operation.
      Type: String
      AllowedValues: 
        - Available
        - Unavailable
        - Maintenance
        - Modifying
        - Failed
      Default: Available
    
    Classic:
      Type: Boolean
      Description: A boolean value indicating whether the resize operation is using the classic resize process or elastic.
      Default: false
    
    ClusterIdentifier: !Ref ClusterIdentifier
    
    ClusterParameterGroupName: !Ref ParameterGroupName
    
    ClusterSecurityGroups: 
      Type: List<String>
      Default: 
        - security-group1
        - security-group2
    
    ClusterSubnetGroupName: !Ref SubnetGroupName

    ClusterType: !Ref ClusterType
    
    ClusterVersion:
      Description: Currently only one version is available
      Type: String
      Default: 1.0
    
    DBName: !Ref DatabaseName
    
    DeferMaintenance: Boolean
    DeferMaintenanceDuration: Integer
    DeferMaintenanceEndTime: String
    DeferMaintenanceStartTime: String
   
    DestinationRegion:
      Description: The destination region that snapshots are automatically copied to when cross-region snapshot copy is enabled.
      Type: String
      Default: us-west-1
    
    ElasticIp:
      Description:
      Type: String
      Default: Elastic-IP
    
    Encrypted:
      Description: Data is encrypted at rest
      Type: Boolean
      Default: true
    
    Endpoint: 
      Address:
        Description: The DNS address of the cluster. This property is read only.
        Type: String
        Default: address
      Port: Integer
    
    EnhancedVpcRouting:
      Description: To create a cluster that uses enhanced VPC routing.
      ConstraintDescription: the cluster must be in a VPC. 
      Type: Boolean
      Default: true
    
    HsmClientCertificateIdentifier:
      Description: Specifies the name of the HSM client certificate the Amazon Redshift cluster uses to retrieve the data encryption keys stored in an HSM.
      Type: String
      Default: hsm-client-identifier-name
    
    HsmConfigurationIdentifier:
      Description: Specifies the name of the HSM configuration that contains the information the Amazon Redshift cluster can use to retrieve and store keys in an HSM.
      Type: String
      Default: hsm-configuration-identifier
    
    IamRoles: 
      - String
    
    KmsKeyId: !Ref KMSKey
    
    LoggingProperties:
      Description: Specifies logging information, such as queries and connection attempts, for the specified Amazon Redshift cluster.
      BucketName: String
      S3KeyPrefix: redshift-logs/
    
    MaintenanceTrackName: String
    
    ManualSnapshotRetentionPeriod:
      Description: Number of days to retain a manual snapshot.
      Type: Integer
      ConstraintDescription: If the value is -1, the snapshot is retained indefinitely.
      MaxValue: 3653
      MinValue: -1
      Default: 30
    
    MasterUsername: !Ref DatabaseMasterUser
    
    MasterUserPassword: !Ref DatabaseMasterPassword
    
    NodeType:
      Type: String
      Default: ds2.xlarge
      Allowedvalues:
        - ds2.xlarge
        - ds2.8xlarge
        - dc1.large
        - dc1.8xlarge
        - dc2.large
        - dc2.8xlarge
        - ra3.xlplus
        - ra3.4xlarge
        - ra3.16xlarge
    NumberOfNodes:
      Type: Integer
      MaxValue: 100
      MinValue: 1
      Default: 4
    
    OwnerAccount: String
    
    Port:
      Description: The port number on which the cluster accepts incoming connections.
      Type: Integer
      MaxValue: 65535
      MinValue: 1150
      Default: 5439
    
    PreferredMaintenanceWindow: String
    
    PubliclyAccessible:
      Description: If true, the cluster can be accessed from a public network.
      Type: Boolean
      Default: true
    
    ResourceAction:
      Type: String
      Allowedvalues:
        - pasue-cluster
        - resume-cluster
      Default: pause-cluster
    
    RevisionTarget: String
    RotateEncryptionKey:
      Description: Rotates the encryption keys for a cluster.
      Type: Boolean
      Default: true
    
    #SnapshotClusterIdentifier: String
    #SnapshotCopyGrantName: String
    
    SnapshotCopyManual:
      Description: Indicates whether to apply the snapshot retention period to newly copied manual snapshots instead of automated snapshots.
      Type: Boolean
      Default: true
    
    SnapshotCopyRetentionPeriod:
      Description: Number of days to retain a snapshot.
      Type: Integer
      ConstraintDescription: If the value is -1, the snapshot is retained indefinitely.
      MaxValue: 3653
      MinValue: -1
      Default: 30
    #SnapshotIdentifier: String
    
    Tags: 
      - Key: String
        Value: String
    
    VpcSecurityGroupIds: 
      - Security-group-id1
      - security-group-id2

Outputs:
  ClusterEndpoint:
    Description: Cluster endpoint
    Value: !Join
      - ':'
      - - !GetAtt 'RedshiftCluster.Endpoint.Address'
        - !GetAtt 'RedshiftCluster.Endpoint.Port'
    ClusterName:
      Description: Name of the Cluster
      Value: !Ref 'RedshiftCluster'
    RedshiftParamaterGroupName:
      Description: Name of redshift parameter group.
      Value: !Ref 'ParameterGroupName'
    RedshiftClusterSubnetGroupName:
      Description: Name of cluster subnet group.
      Value: !Ref 'SubnetGroupName'
